### ISSUE TITLE
How  to  resize MNIST  or  USPS  in  keras?

### ISSUE THREAD

**Issue by 4Statistics** [bbdamodaran/deepJDOT#1]
Hello,I want to   transfer  from  MNIST  to  USPS.
How  to  resize MNIST  or  USPS  in  keras?
Thank  you.

**Comment by bbdamodaran** [comment]
MNIST, and USPS images are resized outside the keras model. that is, after loading the dataset, I resized accordingly

**Comment by 4Statistics** [comment]
> 
> 
> MNIST, and USPS images are resized outside the keras model. that is, after loading the dataset, I resized accordingly

Thank you very much.
