### ISSUE TITLE
Check accuracy on correct learning rate

### ISSUE THREAD

**Issue by offchan42** [bbdamodaran/deepJDOT#10]
According to PR #9, the learning rate was fixed. This issue is created as a reminder that we have to experiment on the demo and SVHN data to see if high accuracy is still obtained with the learning rate change.
After someone experiments and see high accuracy then this issue should be closed.

**Comment by bbdamodaran** [comment]
the accuracy should be same, if you set the "int_lr=0.001" to "int_lr=0.0001".
