### ISSUE TITLE
Can you  release the code for real datasets?Thank you .

### ISSUE THREAD

**Issue by 4Statistics** [bbdamodaran/deepJDOT#2]
Hello.
Can you  release the code for real datasets?such as MNIST or  USPS.
Thank you very much.

**Comment by bbdamodaran** [comment]
thanks for your interest. I will update the codes for real datasets soon.

**Comment by 4Statistics** [comment]
> 
> 
> thanks for your interest. I will update the codes for real datasets soon.

Thank you very much.
