### ISSUE TITLE
Does the embedding function lack of a pooling layer?

### ISSUE THREAD

**Issue by 4Statistics** [bbdamodaran/deepJDOT#3]
Dear Prof. Bharath Bhushan Damodaran,
        In the paper,in page 9 ,about the embedding function _g_,the author show that there is a  fully-connected layer behind the convolutional layers .Whether  it  need a pooling layer between these layers? 
        What 's the pool_size?
        Thank you very much!
        Best regards.

**Comment by bbdamodaran** [comment]
Behind the CNN layers, there is a flattening layer, keras.layers.Flatten()
